id: PC5CA3DA0
initial_creation_type: ocr
source_metadata:
  volumes:
    5a1a68e1088a420fa539a41e7efe8c20:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ཡོན་ཏན་བདུན་ཡོངས་སུ་བརྗོད་པའི་གཏམ།
      total_pages: 1144
      volume_number: 96
